spring:
  datasource:
    url: jdbc:postgresql://ep-rough-heart-a1ho5g1v-pooler.ap-southeast-1.aws.neon.tech/*****?sslmode=require&channelBinding=require
    username: *******
    password: *********


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
